# Generated by Django 2.2.6 on 2019-11-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_adminprefrences_prefrences'),
    ]

    operations = [
        migrations.CreateModel(
            name='LEDMatrixSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('led_matrix_on', models.BooleanField(default=True)),
                ('currently_showing_limit', models.PositiveIntegerField(default=10)),
                ('time_between_drawings', models.PositiveIntegerField(default=10)),
                ('led_matrix_on_time', models.TimeField()),
                ('led_matrix_off_time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='adminprefrences',
            name='user',
        ),
        migrations.DeleteModel(
            name='Prefrences',
        ),
        migrations.DeleteModel(
            name='AdminPrefrences',
        ),
    ]
