# Generated by Django 2.2.6 on 2019-11-16 21:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191116_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledmatrixsettings',
            name='led_matrix_off_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 11, 16, 21, 48, 27, 688657, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='ledmatrixsettings',
            name='led_matrix_on_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 11, 16, 21, 48, 27, 688639, tzinfo=utc), null=True),
        ),
    ]
