# Generated by Django 2.2.6 on 2019-11-17 01:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20191116_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledmatrixsettings',
            name='led_on_off_time_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ledmatrixsettings',
            name='led_matrix_off_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 11, 17, 1, 8, 58, 65382, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='ledmatrixsettings',
            name='led_matrix_on_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 11, 17, 1, 8, 58, 65364, tzinfo=utc), null=True),
        ),
    ]
