# Generated by Django 2.2.6 on 2019-11-17 17:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20191117_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledmatrixsettings',
            name='led_matrix_off_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 11, 17, 17, 21, 20, 908236, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='ledmatrixsettings',
            name='led_matrix_on_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2019, 11, 17, 17, 21, 20, 908217, tzinfo=utc), null=True),
        ),
    ]
