# Generated by Django 2.2.6 on 2019-11-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='drawing_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='submissionshistory',
            name='submission_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
