# Generated by Django 2.2.6 on 2019-11-14 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsubmission',
            old_name='sumbission',
            new_name='submission',
        ),
    ]
